### ISSUE TITLE
info page missing + check your translate page info

### ISSUE THREAD

**Issue by ccppoo** [ArcticaProject/librda#4] opened 2019-04-25 16:33 UTC
![image](https://user-images.githubusercontent.com/46418312/56752249-cd77af00-67c2-11e9-9da0-d2596e68cdfb.png)

error message : 
Can't locate JSON.pm in @INC (you may need to install the JSON module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /srv/sites/arctica-project.org/www/cgi-bin/index.cgi line 24.
BEGIN failed--compilation aborted at /srv/sites/arctica-project.org/www/cgi-bin/index.cgi line 24.

and while translating, your pages are missing and can't see source

**Comment by sunweaver** [comment] 2021-06-07 20:02
@ccppoo: the issue is resolved, probably for a long time. We need to re-do that homepage, really... Closing...

**Closed by sunweaver** 2021-06-07 20:02 UTC
